### ISSUE TITLE
`mv: X and Y are the same file` warning

### ISSUE THREAD

**Issue by eyarz** [datreeio/CRDs-catalog#27]
steps:
1. run the latest version of the CRD Extractor
2. watch script output

expected:
no warning

actual:
`mv: X and Y are the same file` 

![image](https://user-images.githubusercontent.com/19731161/177214007-638b84ac-b670-4423-9349-11eff761b92b.png)

https://askubuntu.com/questions/1143012/why-do-i-get-x-and-y-are-the-same-file-when-using-mv-even-though-they-are-c

**Comment by hadar-co** [comment]
Done

**Comment by eyarz** [comment]
still happening.

What do you think about just ignoring the error?
`mv $0 ${0/\_/-stable-} 2>/dev/null`
I already checked, and it will work.

**Comment by hadar-co** [comment]
Ignoring the error may lead to a failure of the script without us knowing, looking into other solutions first.

**Comment by hadar-co** [comment]
fixed by deleting the folder first, then copying the files.
